### ISSUE TITLE
Erreurs 500 avec plugin Dotclear.watch et PHP 7.4.33

### ISSUE THREAD

**Issue by julmud** [JcDenis/DotclearWatch#4]
Avec Dotclear 2.27.2 et PHP 7.4.33, le plugin dotclear.watch remplit mes logs d'erreurs 500 :
`
[26-Aug-2023 13:17:47 UTC] PHP Fatal error:  Uncaught TypeError: strftime() expects parameter 2 to be int, string given in .../dotclear/src/Helper/Date.php:55
Stack trace:
#0 .../src/Helper/Date.php(55): strftime('%s', '2023-08-26 12:5...')
#1 .../src/Helper/Date.php(266): Dotclear\Helper\Date::strftime('%s', '2023-08-26 12:5...')
#2 .../plugins/DotclearWatch/src/Utils.php(312): Dotclear\Helper\Date::str('%s', '2023-08-26 12:5...')
#3 .../plugins/DotclearWatch/src/Utils.php(167): Dotclear\Plugin\DotclearWatch\Utils::expired()
#4 .../plugins/DotclearWatch/src/Backend.php(53): Dotclear\Plugin\DotclearWatch\Utils::sendReport()
#5 [internal function]: Dotclear\Plugin\DotclearWatch\Backend::Dotclear\Plugin\DotclearWatch\{closure}(Array, Array)
#6 .../src/Helper/RestServer.php(99): call_user_func(Object(Closure), Array, Array)
#7 .../src/Helper/RestServ in /home/mudryorg/mudry.org/dotclear/src/Helper/Date.php on line 55
`

(Par ailleurs, j'ai essayé d'ouvrir ce même ticket sur git.dotclear.watch, mais j'ai une erreur 404 après m'être inscrit lorsque je veux accéder à la page Issues du repo... alors que je n'ai pas d'erreur 404 si j'y accède sans être authentifié.)

**Comment by JcDenis** [comment]
Pour git de dotclear watch pour l'instant je dois valider les inscription (je n'ai pas tout a fait fini de mettre ne place le serveur)

Pour l'erreur je corrige dans la journée. Merci du retour
